### ISSUE TITLE
on_receive hook

### ISSUE THREAD

**Issue by Omie** [kennethreitz/simplemind#13]
This could be useful to embed custom functionality on received messages, for example, content moderation or transformation.

to begin with, I thought we could add the following to `class BasePlugin(ABC)`

```Python
@abstractmethod
def receive_hook(self, message: "Message") -> Message
```

and invoke the same from Conversation.send() as
```Python
for plugin in self.plugins:
    response = plugin.receive_hook(message)
```

this started getting bit complicated very fast. I would certainly appreciate some help to make sure it remains "for humans".

key concerns are:

- plugin may either mutate the message or annotate the same. for example, moderation plugin should just attach the [response](https://platform.openai.com/docs/api-reference/moderations/create) as is or transformation plugin may just modify in place
- multiple plugins could mutate the message. The later one in order may override the earlier one
- multiple plugins could annotate the message and annotations should have some space within Message

questions:
- how should we update `Message` to make space for annotations?
- is mutation ok? order of adding plugins would be order of execution, is that of any concern / undocumented behaviour / makes it hard to debug?
- moderation api is from open ai again. If I were to write a plugin to wrap this, I wouldn't want to maintain API creds separately Is it possible to let plugins use the auth internally?

**Comment by kennethreitz** [comment]
Are you familiar with `r.history` in requests?

**Comment by kennethreitz** [comment]
> Is it possible to let plugins use the auth internally?

Check out this example: https://github.com/kennethreitz/simplemind/blob/main/examples/contextual_memory.py#L80

**Comment by kennethreitz** [comment]
thoughts?

```
class CustomPlugin(BasePlugin):
    def __init__(self):
        self.conversation_history = []

    def initialize_hook(self, conversation):
        """Called when the plugin is first added to a conversation."""
        print("Plugin initialized!")

    def pre_send_hook(self, conversation):
        """Called before the conversation is sent to the AI provider."""
        # Add any system messages or modify the conversation
        conversation.add_message("system", "Remember to be helpful.")

    def send_hook(self, conversation):
        """Called during the send process."""
        # Add messages or modify the conversation
        self.conversation_history.append(conversation.messages)

    def post_send_hook(self, conversation, response):
        """Called after receiving a response from the AI provider."""
        # Process or modify the response
        return response

    def cleanup_hook(self):
        """Called when the plugin is removed or the conversation ends."""
        self.conversation_history.clear()
```

**Comment by kennethreitz** [comment]
check it out!
