### ISSUE TITLE
Support Local Open-Source Models for Offline Use (e.g., LLaMA)

### ISSUE THREAD

**Issue by piotrpawlaczek** [kennethreitz/simplemind#16]
It would be fantastic if `simplemind` could support running local, open-source language models like LLaMA, allowing users to work offline. This could be done using [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) or similar libraries for easy integration with local models.

#### Proposed Changes:

1. Installation: 

Adding a local model dependency could be as simple as:

```bash
>> pip install simplemind[llama-cpp-python]
```

2. Usage: 

Then, to use a local model, users could specify "local" as the llm_provider and choose a specific model like so:

```python
>> sm.generate_text(prompt="What is the meaning of life?", llm_provider="local", llm_model="Meta-Llama-3.2-3B")
```

This would let users switch seamlessly between cloud-based models and offline ones—super helpful for those needing a reliable, private option.

#### Why This Would Be Helpful:

- Privacy: Keeping data local is a big plus for users with privacy concerns.
- Reliability: Many have already Metal/CUDA/Vulcan GPU backend, so why internet?
- Flexibility: Expands `simplemind` to be used across both cloud and offline setups easily.

Thanks for considering this idea!

**Comment by kennethreitz** [comment]
I'd like to rely on https://github.com/simonw/llm, potentially. if @simonw has any thoughts on this approach vs depending on llama-cpp-python, I'd love to hear about it.

**Comment by ErikBjare** [comment]
I used to have something similar as proposed in with `llama-cpp-python` in gptme, but most users were requesting Ollama support, so I ended up removing it and instead simply instruct users to override the `OPENAI_BASE_URL` and set the model to `local/<modelname>` (will check & fail if `OPENAI_BASE_URL` is unset, to ensure no leaked calls to OpenAI).

Here are the docs for it: https://gptme.org/docs/providers.html#local

**Comment by kennethreitz** [comment]
We have an in-progress PR over here for ollama: https://github.com/kennethreitz/simplemind/pull/14

**Comment by kennethreitz** [comment]
ollama is now supported in main
