### ISSUE TITLE
minimum python support version

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [kennethreitz/simplemind#21]
A minimum Python version of 3.11 is a very high bar given that 3.9 still hasn't reached EOL. In my opinion, a minimum version of 3.10 would be more apt given that it introduced a cleaner syntax for type hinting (which we can't use in 3.9)

**Comment by kennethreitz** [comment]
3.10 sounds like a good target to me, too.

**Comment by Siddhesh-Agarwal** [comment]
I have gone through the minimum python support version for all libraries and 3.9 seems to be the highest base version required. This means, we can go with python 3.10

**Comment by kennethreitz** [comment]
okay sounds good! want to send a pr? :)
