### ISSUE TITLE
Too many forced dependencies

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [kennethreitz/simplemind#27]
If someone wants to try simplemind with just the OpenAI client, they are still forced to install all other clients like Groq and Anthropic. Is it possible to make all the client installs optional so that users are not forced to install anything they do not use?

**Comment by Siddhesh-Agarwal** [comment]
Ideally, all the import statements can be shifted inside the `client()` method so that the libraries are not forced dependencies.

**Comment by kennethreitz** [comment]
Great idea. I still want them installed by default, but you’re right we should move the imports to runtime

**Comment by kennethreitz** [comment]
fantastic

**Comment by kennethreitz** [comment]
thanks @Siddhesh-Agarwal
