### ISSUE TITLE
Real-time text streaming

### ISSUE THREAD

**Issue by barisozmen** [kennethreitz/simplemind#33]
I'd like to use simplemind for text streaming use cases. It's a nice UX feature where the user can start seeing/reading responses while it's generated, instead of waiting for its completion. 

I'm preparing a suggestion PR by implementing it for OpenAI. If you like it, I can implement it for other providers as well.

**Comment by kennethreitz** [comment]
@barisozmen wanna help get the others ones integrated?

**Comment by barisozmen** [comment]
I saw your message late. I see you already done it :)
