### ISSUE TITLE
Integrate Pydantic Logfire

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/simplemind#4]
https://pydantic.dev/logfire

**Comment by kennethreitz** [comment]
would like to hear from others about this

**Comment by Siddhesh-Agarwal** [comment]
It seems like a good idea, but we will need manual logging using LogFire since no premade instrument would work. I would like to try this and see where it goes.

**Comment by Siddhesh-Agarwal** [comment]
While logging, is data scrubbing a requirement?
