### ISSUE TITLE
DEFAULT_MODEL and DEFAULT_KWARGS as class variables?

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [kennethreitz/simplemind#41]
This issue is primarily created to know about the intention behind having `DEFAULT_MODEL` and `DEFAULT_KWARGS` as variables inside as well as outside the class. Isn't this just redundant code?

https://github.com/kennethreitz/simplemind/blob/main/simplemind/providers/xai.py#L26-29

**Comment by kennethreitz** [comment]
yes it is

**Comment by kennethreitz** [comment]
welcome cleanup, anytime!

**Comment by Siddhesh-Agarwal** [comment]
Since PR #42 solves this issue, I am closing it.
