### ISSUE TITLE
 [Issue] Installation of simplemind[full] fails due to missing cargo dependency for jiter

### ISSUE THREAD

**Issue by saadmanrafat** [kennethreitz/simplemind#44]
Attempting to install `simplemind[full]` using Poetry fails due to a missing dependency on `cargo`, which is required to build the `jiter` package. This dependency isn't documented, and it causes an installation failure on systems without Rust pre-installed.

## Environment:

- OS: Ubuntu 24.04 LTS
- Python version: 3.13
- Poetry version: 1.8.3

## Reproducing 

`poetry add simplemind[full]`

```bash
Backend subprocess exited when trying to invoke build_wheel

Running `maturin pep517 build-wheel` -i /tmp/tmp8detmmw/.venv/bin/python --compatibility off
...
Caused by: Cargo metadata failed. Do you have cargo in your PATH?
...
error: command ['maturin', 'pep517', 'build-wheel', '-i', '/tmp/tmp8detmmw/.venv/bin/python', '--compatibility', 'off'] returned non-zero exit status 1

Note: This error originates from the build backend, and is likely not a problem with poetry but with jiter (0.5.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "jiter (==0.5.0)"'.
```

I got around the issue installing Rust and cargo separately! Don't want to post the workaround here cause it might not be applicable for everyone. Rather leave it to the maintainers! 

Hope the information helped! 

Thanks!

**Comment by kennethreitz** [comment]
Do you know which dependency is requiring 'jitter'?

**Comment by saadmanrafat** [comment]
Apologies about the typo, I'm editting it. The name of the package is [`jiter`](https://pypi.org/project/jiter/). And the dependency is `instructor`

**Comment by kennethreitz** [comment]
@saadmanrafat are you on python 3.13?

**Comment by saadmanrafat** [comment]
> @saadmanrafat are you on python 3.13?
Yes! I just noticed that `jiter` doesn’t have compatibility with Python 3.13 yet. I’ll go ahead and close the issue for now. Apologies for the oversight, and thank you for your quick response!

**Comment by kennethreitz** [comment]
absolutely! happy to help!
